# Generated by Django 6.0.3 on 2026-04-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='membre',
            name='poste_bureau_general',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='poste_section',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
