# Generated by Django 6.0.3 on 2026-04-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_membre_niveau_etude_membre_numero_telephone_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['membre'], name='caisse_coti_membre__31afec_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['type'], name='caisse_coti_type_5f22d0_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['date'], name='caisse_coti_date_8d26e2_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['section'], name='caisse_depe_section_a1a405_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['date'], name='caisse_depe_date_e125fc_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['nom', 'prenom'], name='caisse_memb_nom_336389_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['section'], name='caisse_memb_section_63800f_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['est_membre_bureau_general'], name='caisse_memb_est_mem_9515d0_idx'),
        ),
    ]
