# Generated by Django 6.0.3 on 2026-04-19 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_cotisation_caisse_coti_membre__31afec_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutreArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'autre argent',
                'verbose_name_plural': 'autres argents',
            },
        ),
        migrations.CreateModel(
            name='ResteAncienneCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'reste ancienne caisse',
                'verbose_name_plural': 'restes ancienne caisse',
            },
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='type',
            field=models.CharField(choices=[('ANNUELLE', 'Annuelle'), ('BOOSTER', 'Autre cotisation')], max_length=8),
        ),
        migrations.CreateModel(
            name='DemandeCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.membre')),
            ],
            options={
                'verbose_name': 'demande de carte',
                'verbose_name_plural': 'demandes de carte',
            },
        ),
    ]
